server:
  port: 8888


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8700/eureka


spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: asdad
          ignore-local-ssh-settings: true
          strict-host-key-cheking: false
          search-paths:
            - configuration/{application}/
            - configuration/
          private-key:
            sldkja
